### ISSUE TITLE
Error during direct call to /auth in fastapi/starlette impementation

### ISSUE THREAD

**Issue by ioparaskev** [authlib/demo-oauth-client#11]
I'm trying out the examples that are here for google login with starlette and fastapi. When I follow the normal flow everything works as expected. But if for example I try to access directly the `/auth` url the application crashes with the following stacktrace:

```
INFO:     127.0.0.1:41144 - "GET /auth HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "./app.py", line 46, in auth
    token = await oauth.google.authorize_access_token(request)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/authlib/integrations/starlette_client/integration.py", line 62, in authorize_access_token
    params = self.retrieve_access_token_params(request)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/authlib/integrations/base_client/base_app.py", line 145, in retrieve_access_token_params
    params = self._retrieve_oauth2_access_token_params(request, params)
  File "/home/jpr/.virtualenvs/tmp-61b723d80f5058/lib/python3.7/site-packages/authlib/integrations/base_client/base_app.py", line 126, in _retrieve_oauth2_access_token_params
    raise MismatchingStateError()
authlib.integrations.base_client.errors.MismatchingStateError: mismatching_state: CSRF Warning! State not equal in request and response.
```

which in a way is expected since the `authorize_redirect` part was skipped. So my question is two-fold:
1. Is this really expected behavior? This actually results in a server error which means that someone could take advantage of it
2. If this is expected behavior, what's the suggested way to restrict access to `/auth` ? Since the user is currently not logged in, is there a way to enforce the correct flow?

**Comment by lepture** [comment]
@ioparaskev you can add a `try ` expression in your code.

I've updated the example: https://github.com/authlib/demo-oauth-client/commit/95373ab4206067acce3117c40f4a9d165430b576
